# Generated by ariadne-codegen

from .base_operation import GraphQLField


class AnalyticsFieldGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AnalyticsFieldGraphQLField":
        self._alias = alias
        return self


class AnalyticsFieldsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AnalyticsFieldsConnectionGraphQLField":
        self._alias = alias
        return self


class AskDataExtensionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AskDataExtensionGraphQLField":
        self._alias = alias
        return self


class AskDataExtensionsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "AskDataExtensionsConnectionGraphQLField":
        self._alias = alias
        return self


class BinFieldGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "BinFieldGraphQLField":
        self._alias = alias
        return self


class BinFieldsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "BinFieldsConnectionGraphQLField":
        self._alias = alias
        return self


class CalculatedFieldGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CalculatedFieldGraphQLField":
        self._alias = alias
        return self


class CalculatedFieldsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CalculatedFieldsConnectionGraphQLField":
        self._alias = alias
        return self


class CanHaveLabelsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CanHaveLabelsGraphQLField":
        self._alias = alias
        return self


class CanHaveLabelsesConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CanHaveLabelsesConnectionGraphQLField":
        self._alias = alias
        return self


class CertifiableGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CertifiableGraphQLField":
        self._alias = alias
        return self


class CertifiablesConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CertifiablesConnectionGraphQLField":
        self._alias = alias
        return self


class CloudFileGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CloudFileGraphQLField":
        self._alias = alias
        return self


class CloudFilesConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CloudFilesConnectionGraphQLField":
        self._alias = alias
        return self


class ColumnGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ColumnGraphQLField":
        self._alias = alias
        return self


class ColumnFieldGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ColumnFieldGraphQLField":
        self._alias = alias
        return self


class ColumnFieldsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ColumnFieldsConnectionGraphQLField":
        self._alias = alias
        return self


class ColumnsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ColumnsConnectionGraphQLField":
        self._alias = alias
        return self


class CombinedFieldGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CombinedFieldGraphQLField":
        self._alias = alias
        return self


class CombinedFieldsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CombinedFieldsConnectionGraphQLField":
        self._alias = alias
        return self


class CombinedSetFieldGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CombinedSetFieldGraphQLField":
        self._alias = alias
        return self


class CombinedSetFieldsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CombinedSetFieldsConnectionGraphQLField":
        self._alias = alias
        return self


class CustomSQLTableGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CustomSQLTableGraphQLField":
        self._alias = alias
        return self


class CustomSQLTablesConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "CustomSQLTablesConnectionGraphQLField":
        self._alias = alias
        return self


class DashboardGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DashboardGraphQLField":
        self._alias = alias
        return self


class DashboardsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DashboardsConnectionGraphQLField":
        self._alias = alias
        return self


class DataCloudGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DataCloudGraphQLField":
        self._alias = alias
        return self


class DataCloudsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DataCloudsConnectionGraphQLField":
        self._alias = alias
        return self


class DataFieldGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DataFieldGraphQLField":
        self._alias = alias
        return self


class DataFieldsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DataFieldsConnectionGraphQLField":
        self._alias = alias
        return self


class DataQualityCertificationGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DataQualityCertificationGraphQLField":
        self._alias = alias
        return self


class DataQualityCertificationsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DataQualityCertificationsConnectionGraphQLField":
        self._alias = alias
        return self


class DataQualityWarningGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DataQualityWarningGraphQLField":
        self._alias = alias
        return self


class DataQualityWarningsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DataQualityWarningsConnectionGraphQLField":
        self._alias = alias
        return self


class DatabaseGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DatabaseGraphQLField":
        self._alias = alias
        return self


class DatabaseServerGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DatabaseServerGraphQLField":
        self._alias = alias
        return self


class DatabaseServersConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DatabaseServersConnectionGraphQLField":
        self._alias = alias
        return self


class DatabaseTableGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DatabaseTableGraphQLField":
        self._alias = alias
        return self


class DatabaseTablesConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DatabaseTablesConnectionGraphQLField":
        self._alias = alias
        return self


class DatabasesConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DatabasesConnectionGraphQLField":
        self._alias = alias
        return self


class DatasourceGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DatasourceGraphQLField":
        self._alias = alias
        return self


class DatasourceFieldGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DatasourceFieldGraphQLField":
        self._alias = alias
        return self


class DatasourceFieldsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DatasourceFieldsConnectionGraphQLField":
        self._alias = alias
        return self


class DatasourceFilterGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DatasourceFilterGraphQLField":
        self._alias = alias
        return self


class DatasourceFiltersConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DatasourceFiltersConnectionGraphQLField":
        self._alias = alias
        return self


class DatasourcesConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "DatasourcesConnectionGraphQLField":
        self._alias = alias
        return self


class EmbeddedDatasourceGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "EmbeddedDatasourceGraphQLField":
        self._alias = alias
        return self


class EmbeddedDatasourcesConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "EmbeddedDatasourcesConnectionGraphQLField":
        self._alias = alias
        return self


class FieldGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FieldGraphQLField":
        self._alias = alias
        return self


class FieldReferencingFieldGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FieldReferencingFieldGraphQLField":
        self._alias = alias
        return self


class FieldReferencingFieldsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FieldReferencingFieldsConnectionGraphQLField":
        self._alias = alias
        return self


class FieldsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FieldsConnectionGraphQLField":
        self._alias = alias
        return self


class FileGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FileGraphQLField":
        self._alias = alias
        return self


class FilesConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FilesConnectionGraphQLField":
        self._alias = alias
        return self


class FlowGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FlowGraphQLField":
        self._alias = alias
        return self


class FlowColumnInputFieldGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FlowColumnInputFieldGraphQLField":
        self._alias = alias
        return self


class FlowColumnInputFieldsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FlowColumnInputFieldsConnectionGraphQLField":
        self._alias = alias
        return self


class FlowColumnOutputFieldGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FlowColumnOutputFieldGraphQLField":
        self._alias = alias
        return self


class FlowColumnOutputFieldsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FlowColumnOutputFieldsConnectionGraphQLField":
        self._alias = alias
        return self


class FlowFieldInputFieldGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FlowFieldInputFieldGraphQLField":
        self._alias = alias
        return self


class FlowFieldInputFieldsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FlowFieldInputFieldsConnectionGraphQLField":
        self._alias = alias
        return self


class FlowFieldOutputFieldGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FlowFieldOutputFieldGraphQLField":
        self._alias = alias
        return self


class FlowFieldOutputFieldsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FlowFieldOutputFieldsConnectionGraphQLField":
        self._alias = alias
        return self


class FlowInputFieldGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FlowInputFieldGraphQLField":
        self._alias = alias
        return self


class FlowInputFieldsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FlowInputFieldsConnectionGraphQLField":
        self._alias = alias
        return self


class FlowOutputFieldGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FlowOutputFieldGraphQLField":
        self._alias = alias
        return self


class FlowOutputFieldsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FlowOutputFieldsConnectionGraphQLField":
        self._alias = alias
        return self


class FlowOutputStepGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FlowOutputStepGraphQLField":
        self._alias = alias
        return self


class FlowOutputStepsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FlowOutputStepsConnectionGraphQLField":
        self._alias = alias
        return self


class FlowsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "FlowsConnectionGraphQLField":
        self._alias = alias
        return self


class GenericLabelGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "GenericLabelGraphQLField":
        self._alias = alias
        return self


class GenericLabelsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "GenericLabelsConnectionGraphQLField":
        self._alias = alias
        return self


class GroupFieldGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "GroupFieldGraphQLField":
        self._alias = alias
        return self


class GroupFieldsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "GroupFieldsConnectionGraphQLField":
        self._alias = alias
        return self


class HierarchyFieldGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "HierarchyFieldGraphQLField":
        self._alias = alias
        return self


class HierarchyFieldsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "HierarchyFieldsConnectionGraphQLField":
        self._alias = alias
        return self


class InheritedStringResultGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "InheritedStringResultGraphQLField":
        self._alias = alias
        return self


class LabelGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "LabelGraphQLField":
        self._alias = alias
        return self


class LabelsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "LabelsConnectionGraphQLField":
        self._alias = alias
        return self


class LensGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "LensGraphQLField":
        self._alias = alias
        return self


class LensFieldGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "LensFieldGraphQLField":
        self._alias = alias
        return self


class LensFieldsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "LensFieldsConnectionGraphQLField":
        self._alias = alias
        return self


class LensesConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "LensesConnectionGraphQLField":
        self._alias = alias
        return self


class LinkedFlowGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "LinkedFlowGraphQLField":
        self._alias = alias
        return self


class LinkedFlowsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "LinkedFlowsConnectionGraphQLField":
        self._alias = alias
        return self


class MetricGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MetricGraphQLField":
        self._alias = alias
        return self


class MetricDefinitionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MetricDefinitionGraphQLField":
        self._alias = alias
        return self


class MetricDefinitionsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MetricDefinitionsConnectionGraphQLField":
        self._alias = alias
        return self


class MetricsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "MetricsConnectionGraphQLField":
        self._alias = alias
        return self


class NodeGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "NodeGraphQLField":
        self._alias = alias
        return self


class NodesConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "NodesConnectionGraphQLField":
        self._alias = alias
        return self


class PageInfoGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "PageInfoGraphQLField":
        self._alias = alias
        return self


class ParameterGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ParameterGraphQLField":
        self._alias = alias
        return self


class ParametersConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ParametersConnectionGraphQLField":
        self._alias = alias
        return self


class PublishedDatasourceGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "PublishedDatasourceGraphQLField":
        self._alias = alias
        return self


class PublishedDatasourcesConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "PublishedDatasourcesConnectionGraphQLField":
        self._alias = alias
        return self


class SetFieldGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SetFieldGraphQLField":
        self._alias = alias
        return self


class SetFieldsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SetFieldsConnectionGraphQLField":
        self._alias = alias
        return self


class SheetGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SheetGraphQLField":
        self._alias = alias
        return self


class SheetsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "SheetsConnectionGraphQLField":
        self._alias = alias
        return self


class TableGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TableGraphQLField":
        self._alias = alias
        return self


class TableAdditionalDetailsGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TableAdditionalDetailsGraphQLField":
        self._alias = alias
        return self


class TableAdditionalDetailsesConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TableAdditionalDetailsesConnectionGraphQLField":
        self._alias = alias
        return self


class TableauSiteGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TableauSiteGraphQLField":
        self._alias = alias
        return self


class TableauSitesConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TableauSitesConnectionGraphQLField":
        self._alias = alias
        return self


class TableauUserGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TableauUserGraphQLField":
        self._alias = alias
        return self


class TableauUsersConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TableauUsersConnectionGraphQLField":
        self._alias = alias
        return self


class TablesConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TablesConnectionGraphQLField":
        self._alias = alias
        return self


class TagGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TagGraphQLField":
        self._alias = alias
        return self


class TaggableGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TaggableGraphQLField":
        self._alias = alias
        return self


class TaggablesConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TaggablesConnectionGraphQLField":
        self._alias = alias
        return self


class TagsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "TagsConnectionGraphQLField":
        self._alias = alias
        return self


class ViewGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ViewGraphQLField":
        self._alias = alias
        return self


class ViewsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "ViewsConnectionGraphQLField":
        self._alias = alias
        return self


class VirtualConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "VirtualConnectionGraphQLField":
        self._alias = alias
        return self


class VirtualConnectionTableGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "VirtualConnectionTableGraphQLField":
        self._alias = alias
        return self


class VirtualConnectionTablesConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "VirtualConnectionTablesConnectionGraphQLField":
        self._alias = alias
        return self


class VirtualConnectionsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "VirtualConnectionsConnectionGraphQLField":
        self._alias = alias
        return self


class WarnableGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "WarnableGraphQLField":
        self._alias = alias
        return self


class WarnablesConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "WarnablesConnectionGraphQLField":
        self._alias = alias
        return self


class WebDataConnectorGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "WebDataConnectorGraphQLField":
        self._alias = alias
        return self


class WebDataConnectorsConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "WebDataConnectorsConnectionGraphQLField":
        self._alias = alias
        return self


class WorkbookGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "WorkbookGraphQLField":
        self._alias = alias
        return self


class WorkbooksConnectionGraphQLField(GraphQLField):
    def alias(self, alias: str) -> "WorkbooksConnectionGraphQLField":
        self._alias = alias
        return self
