# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2025-01-13T14:09:31+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional


@dataclass
class QueryType:
    name: str


@dataclass
class Type1:
    kind: str
    name: str
    ofType: None


@dataclass
class Arg:
    name: str
    description: Optional[str]
    type: Type1
    defaultValue: Optional[str]
    isDeprecated: bool
    deprecationReason: None


@dataclass
class OfType2:
    kind: str
    name: str
    ofType: None


@dataclass
class OfType1:
    kind: str
    name: Optional[str]
    ofType: Optional[OfType2]


@dataclass
class OfType:
    kind: str
    name: Optional[str]
    ofType: Optional[OfType1]


@dataclass
class Type2:
    kind: str
    name: Optional[str]
    ofType: Optional[OfType]


@dataclass
class Field:
    name: str
    description: Optional[str]
    args: List[Arg]
    type: Type2
    isDeprecated: bool
    deprecationReason: Optional[str]


@dataclass
class OfType3:
    kind: str
    name: str
    ofType: None


@dataclass
class Type3:
    kind: str
    name: Optional[str]
    ofType: Optional[OfType3]


@dataclass
class InputField:
    name: str
    description: str
    type: Type3
    defaultValue: None
    isDeprecated: bool
    deprecationReason: None


@dataclass
class Interface:
    kind: str
    name: str
    ofType: None


@dataclass
class EnumValue:
    name: str
    description: Optional[str]
    isDeprecated: bool
    deprecationReason: None


@dataclass
class PossibleType:
    kind: str
    name: str
    ofType: None


@dataclass
class Type:
    kind: str
    name: str
    description: str
    fields: Optional[List[Field]]
    inputFields: Optional[List[InputField]]
    interfaces: Optional[List[Interface]]
    enumValues: Optional[List[EnumValue]]
    possibleTypes: Optional[List[PossibleType]]


@dataclass
class Type4:
    kind: str
    name: Optional[str]
    ofType: Optional[OfType3]


@dataclass
class Arg1:
    name: str
    description: str
    type: Type4
    defaultValue: Optional[str]
    isDeprecated: bool
    deprecationReason: None


@dataclass
class Directive:
    name: str
    description: str
    isRepeatable: bool
    locations: List[str]
    args: List[Arg1]


@dataclass
class FieldSchema:
    description: None
    queryType: QueryType
    mutationType: None
    subscriptionType: None
    types: List[Type]
    directives: List[Directive]


@dataclass
class Model:
    field__schema: FieldSchema
