# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2025-01-13T14:09:32+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class QueryType(BaseModel):
    name: str


class Type1(BaseModel):
    kind: str
    name: str
    ofType: None


class Arg(BaseModel):
    name: str
    description: Optional[str]
    type: Type1
    defaultValue: Optional[str]
    isDeprecated: bool
    deprecationReason: None


class OfType2(BaseModel):
    kind: str
    name: str
    ofType: None


class OfType1(BaseModel):
    kind: str
    name: Optional[str]
    ofType: Optional[OfType2]


class OfType(BaseModel):
    kind: str
    name: Optional[str]
    ofType: Optional[OfType1]


class Type2(BaseModel):
    kind: str
    name: Optional[str]
    ofType: Optional[OfType]


class FieldModel(BaseModel):
    name: str
    description: Optional[str]
    args: List[Arg]
    type: Type2
    isDeprecated: bool
    deprecationReason: Optional[str]


class OfType3(BaseModel):
    kind: str
    name: str
    ofType: None


class Type3(BaseModel):
    kind: str
    name: Optional[str]
    ofType: Optional[OfType3]


class InputField(BaseModel):
    name: str
    description: str
    type: Type3
    defaultValue: None
    isDeprecated: bool
    deprecationReason: None


class Interface(BaseModel):
    kind: str
    name: str
    ofType: None


class EnumValue(BaseModel):
    name: str
    description: Optional[str]
    isDeprecated: bool
    deprecationReason: None


class PossibleType(BaseModel):
    kind: str
    name: str
    ofType: None


class Type(BaseModel):
    kind: str
    name: str
    description: str
    fields: Optional[List[FieldModel]]
    inputFields: Optional[List[InputField]]
    interfaces: Optional[List[Interface]]
    enumValues: Optional[List[EnumValue]]
    possibleTypes: Optional[List[PossibleType]]


class Type4(BaseModel):
    kind: str
    name: Optional[str]
    ofType: Optional[OfType3]


class Arg1(BaseModel):
    name: str
    description: str
    type: Type4
    defaultValue: Optional[str]
    isDeprecated: bool
    deprecationReason: None


class Directive(BaseModel):
    name: str
    description: str
    isRepeatable: bool
    locations: List[str]
    args: List[Arg1]


class FieldSchema(BaseModel):
    description: None
    queryType: QueryType
    mutationType: None
    subscriptionType: None
    types: List[Type]
    directives: List[Directive]


class Model(BaseModel):
    field__schema: FieldSchema = Field(..., alias='__schema')
